### ISSUE TITLE
(MC1.10.2-babymobs1.5.3) server crash with zombie chicken riders

### ISSUE THREAD

**Issue by rustyiron99** [Furgl/BabyMobs#4]
MC 1.10.2
Java 1.8.0_60
forge-1.10.2-12.18.3.2185-universal
BabyMobs-1.10.2-1.5.3

Getting a recurring SMP server crash when players are killed by a zombie chicken rider.

Here's a copy of the crash report:

[crash-2016-12-20_00.08.52-server.txt](https://github.com/Furgl/BabyMobs/files/662922/crash-2016-12-20_00.08.52-server.txt)

**Comment by Furgl** [comment]
From what I can tell by tracing the crash, it doesn't appear to be related to Baby Mobs. The crash is caused by the TombManyGraves mod; [this code](https://github.com/M4thG33k/TombManyGraves/blob/d3d2e050d9997dbea2cd1fd44d6137272daa5579/src/main/java/com/m4thg33k/tombmanygraves/tiles/TileDeathBlock.java#L877-L881) in particular. It looks like the mod is scanning the player's inventory after death and encounters an item with a null enchantment that throws the null pointer. 

I can't replicate the crash with Baby Mobs, TombManyGraves, EnderIO, and EnderCore installed, so I can't know for sure, but I would assume that this crash is related to a specific item in the player's inventory when they die. If that doesn't appear to be the case, I can try to replicate the crash if you give me the mod pack that it happens in.

**Comment by rustyiron99** [comment]
thank you for the explanation and help tracing this.  i am no expert on reading the crash files and it only seemed to be happening with that one mob (3 times so far) but coincidences do happen.  will try checking for a bugged item next.  if it is not an item and i am able to reliably replicate the conditions i will post again with the details.

thanks for the quick reply.  love the mod.

**Comment by Furgl** [comment]
No problem, I'm glad you're enjoying the mod!
